package com.jose.ejercicio_1_28_2022.Utilidades;

public class Literals {
	public static String basePath = ".";
	public static String historicoPath = "./busquedas.dat";
	public static String datos_path = "./datos.csv";
	public static String wrongFormat = "Formato incorrecto, pruebe a introducir de nuevo";
	public static String errorLatitud = "\nLa latitud de ser un número entre -90 y 90, ambos inclusive.";
	public static String errorLongitud = "\nLa longitud debe ser un número entre -180 y 180, ambos inclusive.";
	public static String deleting = "Eliminando duplicado";
	public static String deleted = "Eliminación completada.";
	public static String nothing_serialize = "No hay búsquedas para serializar.";
	public static String serializing = "Serializando...";
	public static String serialize_ok = "Búsquedas recientes serializadas con éxito.";
	public static String error = "ERROR";
	public static String history_list = "Lista de búsquedas almacenadas:";
	public static String total_goals = "Goles totales del %s = %2s";
	public static String insert_local = "\nIntroduzca el nombre del equipo local";
	public static String insert_visitant = "\nIntroduzca el nombre del equipo visitante";
	public static String insert_start_date = "\nIntroduzca la fecha inicial con formato dd/mm/yyyy:";
	public static String insert_end_date = "\nIntroduzca la fecha final con formato dd/mm/yyyy:";
	public static String history_count = "Total de Registros: %s";
	public static String menu_title = "\nMenú (Selecione una opción)";
    public static String menu_1 = "1. Obtener información en base a unas coordenadas.";
    public static String menu_2 = "2. Obtener información en una localidad determinada.";
    public static String menu_3 = "3. Obterner información en una fecha determinada.";
    public static String menu_4 = "4. Guardar datos de las búsquedas.";
    public static String menu_5 = "5. Mostrar búsquedas guardadas."; 
    public static String menu_6 = "6. Obtener enfrentamientos entre 2 equipos de fútbol"; 
    public static String menu_exit = "0. Salir"; 
	public static String error_no_num = "\n***El valor introducido no es un número";
    public static String urlBase = "https://api.openweathermap.org/data/2.5/weather?";
    public static String tokenWeather = "&appid=871a1c2012aa13906ae6b27ae2aff30b";
	public static String urlBaseFutbol = "https://www.thesportsdb.com/api/v1/json/2/searchevents.php?e=";
	public static String url_vs = "_vs_";
	public static String url_longitude = "&lon=";
	public static String url_latitude = "lat=";
	public static String insert_lat = "Introducir latitud:";
	public static String insert_lon = "Introducir longitud:";
	public static String insert_city = "Introducir localidad:";
	public static String urlCity = "q=";
	public static String urlXml = "&mode=xml";
	public static String choose_option = "\n***Debe seleccionar una de las opciones propuestas.";
	public static String continue_exit = "\nPulse C para continuar o S para salir\n";
	public static String app_closed = "\nAplicación cerrada. Hasta pronto!!!";
}
