package com.jose.dam.spring.mvc.entity;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;

/**
 * Categories generated by hbm2java
 */
@Entity
@Table(name = "categories")
public class Categories implements Serializable {

	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	@Column(name = "category")
	private String category;
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categories")
	private Set<Jokes> jokeses = new HashSet<Jokes>(0);

	public Categories() {
	}

	public Categories(String category) {
		this.category = category;
	}

	public Categories(String category, Set<Jokes> jokeses) {
		this.category = category;
		this.jokeses = jokeses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categories")
	public Set<Jokes> getJokeses() {
		return this.jokeses;
	}

	public void setJokeses(Set<Jokes> jokeses) {
		this.jokeses = jokeses;
	}

	@Override
	public String toString() {
		String resultado = "Id: "  + id  + "\n";
		resultado += "Categoría: "  + category  + "\n";
		if (jokeses.size()>0) {
			resultado += "Listado de Id's de jokes con categoría " + category + ":\n";
			for (Jokes joke : jokeses) {
				resultado += joke.getId() + "\n";
			} 
		} else {
			resultado += "Esta categoría no tiene ningún joke";
		}
		return resultado;
	}

	@Override
	public int hashCode() {
		return Objects.hash(id);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Categories other = (Categories) obj;
		return id == other.id;
	}
}
