package com.jose.dam.spring.mvc.entity;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;

/**
 * Flags generated by hbm2java
 */
@Entity
@Table(name = "flags")
//@JsonIgnoreProperties("jokeses")
public class Flags implements Serializable {

	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	@Column(name = "flag")
	private String flag;
	@ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "jokes_flags", joinColumns = {
            @JoinColumn(name = "flag_id", nullable = false, updatable = false) }, inverseJoinColumns = {
                    @JoinColumn(name = "joke_id", nullable = false, updatable = false) })
	private Set<Jokes> jokeses = new HashSet<Jokes>(0);

	public Flags() {
	}

	public Flags(String flag) {
		this.flag = flag;
	}

	public Flags(String flag, Set<Jokes> jokeses) {
		this.flag = flag;
		this.jokeses = jokeses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}
	
	public Set<Jokes> getJokeses() {
		return this.jokeses;
	}

	public void setJokeses(Set<Jokes> jokeses) {
		this.jokeses = jokeses;
	}

	@Override
	public String toString() {
		return "Flag ID= " + id + " => " + flag;
	}

}
